# https://www.mkdocs.org/user-guide/configuration/

site_name: Valhalla
repo_url: https://github.com/valhalla/valhalla/
nav:
  - Introduction: valhalla-intro.md
  - Terminology: terminology.md
  - API:
    - Turn-by-Turn Route API: api/turn-by-turn/api-reference.md
    - Map Matching API: api/map-matching/api-reference.md
    - Locate API: api/locate/api-reference.md
    - Matrix API: api/matrix/api-reference.md
    - Optimized Route API: api/optimized/api-reference.md
    - Elevation API: api/elevation/api-reference.md
    - Isochrone API: api/isochrone/api-reference.md
  - Internals:
    - Decoding shape: decoding.md
    - Tile structure: tiles.md
    - Speed information: speeds.md
    - "Why tiles?": mjolnir/why_tiles.md
    - OSM connectivity map: connectivity.md
    - Dynamic costing: sif/dynamic-costing.md
    - Elevation influenced bicycle routing: sif/elevation_costing.md
  - Data sources:
    - Data sources: mjolnir/data_sources.md
    - Administrative data: mjolnir/admins.md
    - Attribution requirements: mjolnir/attribution.md
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True